name: Build and eMail

env:
  typst_version: "v0.10.0"

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install typst
        run: |
          curl -L https://github.com/typst/typst/releases/download/${typst_version}/typst-x86_64-unknown-linux-musl.tar.xz --output typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf typst-x86_64-unknown-linux-musl.tar.xz
          cd typst-x86_64-unknown-linux-musl
          sudo mv typst /usr/local/bin/

      - name: Run typst
        run: |
          typst compile --font-path ./fonts resume.typ
          typst compile --font-path ./fonts cv.typ
  
  email:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: eMail files
        run: |
          ls -lah
